### ISSUE TITLE
Schemas break the rule of actions being serializable

### ISSUE THREAD

**Issue by PachowStudios** [michaelkrone/ngrx-normalizr#16]
Normalizr's schema objects aren't serializable.

Instead of having the action hang on to the schema and doing the normalization in the reducer, the normalization should be done in the action's constructor (just like a classic action creator) which then puts the normalized entities in the action's payload. That way, the action is completely serializable at the time it's dispatched.

**Comment by michaelkrone** [comment]
Hello @PachowStudios 
Your point is absolutely valid, I just did not think of this. I will look into this.

**Comment by michaelkrone** [comment]
As far as I see, the API  can stay unchanged, but the interfaces are changing, so this will be a v2.0.0 release.

**Comment by PachowStudios** [comment]
Awesome! Thanks for taking care of it
