### ISSUE TITLE
Deleting items does not remove them from the parent

### ISSUE THREAD

**Issue by tommueller** [michaelkrone/ngrx-normalizr#24]
When I delete something from my store using the RemoveData-action the item gets deleted from the store, but the reference from the parent does not get removed.

Examples

`{
    "id": "page1",
    "sections": [{
        "id": "section1"
    }]
}`
normalizr turns this into: 

`{
  normalized: {
    result: [
      'page1'
    ],
    entities: {
      sections: {
        sektion1: {
          id: 'sektion1'
        }
      },
      pages: {
        seite1: {
          id: 'seite1',
          sections: ['sektion1']
       }
      } 
   } 
}`

Now I run `this.store.dispatch(new RemoveData({ id: section.id, schema: sectionSchema }));` which leads to the following state: 
`{
  normalized: {
    result: [
      'page1'
    ],
    entities: {
      sections: {
      },
      pages: {
        seite1: {
          id: 'seite1',
          sections: ['sektion1']
       }
      } 
   } 
}`

Which obviously breaks the code then ... any ideas why this is happening?

**Comment by michaelkrone** [comment]
Please see #20 
`RemoveChildData` support is comming in v2.2.0

**Comment by tommueller** [comment]
@michaelkrone working fine for me as well! Thanks for the fast fixes!

**Comment by pierresigwalt** [comment]
Hi,

The issue persist, When using RemoveChildData it's deleted well the child but the reference inside the parent still there.

Before Remove child Data
![screen shot 2018-06-04 at 11 53 44 am](https://user-images.githubusercontent.com/8101858/40897526-1b74a508-67ee-11e8-8cea-267000a177ab.png)

After Remove child data


![screen shot 2018-06-04 at 11 53 55 am](https://user-images.githubusercontent.com/8101858/40897529-1e098540-67ee-11e8-8b11-f8b03d7c715f.png)


As we can see the group schema inside Policy still have the id.

Thank you.
